export const listOfOrchids = [{
    "id": "1",
    "name": "Hoa lan tím",
    "desc": "Loài hoa lan mang sắc tím dịu dàng, tượng trưng cho sự thủy chung và sang trọng.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://media.istockphoto.com/id/1369976302/vi/anh/n%E1%BB%81n-hoa-lan-t%C3%ADm-tuy%E1%BB%87t-%C4%91%E1%BA%B9p-phalaenopsis.jpg?s=612x612&w=0&k=20&c=mi4SEyT-DnABKrfiH9rKUusd1uZOsFBcMGCoV8zvSfI=",
    "color": "purple",
    "numberOfLike": 134,
    "origin": "Vietnam",
    "category": "Phalaenopsis"
  },
  {
    "id": "2",
    "name": "Hoa lan trắng",
    "desc": "Hoa lan trắng biểu tượng cho sự tinh khiết, thanh lịch và nhẹ nhàng.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://media.istockphoto.com/id/2174155023/vi/anh/plumeria-tr%E1%BA%AFng.jpg?s=612x612&w=0&k=20&c=49gGBA-nOtsPUMI4T1iEWio9bJhOog1WT4Mvs5Vb7Ew=",
    "color": "white",
    "numberOfLike": 98,
    "origin": "Vietnam",
    "category": "Phalaenopsis"
  },
  {
    "id": "4",
    "name": "Hoa lan hồng",
    "desc": "Hoa lan hồng mang vẻ đẹp ngọt ngào, lãng mạn và đầy nữ tính.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://lillyflower.com.vn/wp-content/uploads/2023/11/lan-ho-diep-hong.jpeg",
    "color": "pink",
    "numberOfLike": 175,
    "origin": "Taiwan",
    "category": "Phalaenopsis"
  },
  {
    "id": "5",
    "name": "Hoa lan xanh",
    "desc": "Một loài lan hiếm với màu xanh độc đáo, tượng trưng cho sự sáng tạo.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://cdn.f20beauty.com/26078/hoa-lan-ho-diep-mau-xanh.jpg",
    "color": "blue",
    "numberOfLike": 100,
    "origin": "Thailand",
    "category": "Phalaenopsis"
  },
  {
    "id": "6",
    "name": "Lan hồ điệp",
    "desc": "Lan hồ điệp nổi tiếng với vẻ đẹp quý phái và thời gian nở hoa lâu.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": true,
    "image": "https://cdnv2.tgdd.vn/bhx-static/bhx/News/Images/2025/11/24/1586140/image14_202511240039110604.jpg",
    "color": "pink",
    "numberOfLike": 312,
    "origin": "Taiwan",
    "category": "Phalaenopsis"
  },
  {
    "id": "7",
    "name": "Lan dendro",
    "desc": "Lan dendro có sức sống mạnh mẽ như những vũ công Samba và màu sắc đa dạng.",
    "rating": 3,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://cdn.eva.vn/upload/3-2022/images/2022-07-22/image11-1658476169-15-width2048height1365.jpg",
    "color": "purple",
    "numberOfLike": 88,
    "origin": "Vietnam",
    "category": "Dendrobium"
  },
  {
    "id": "8",
    "name": "Lan vũ nữ",
    "desc": "Những cánh hoa mềm mại như vũ công đang nhảy múa trong gió.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://vuonlankhanhnguyen.com/wp-content/uploads/hoalanvunu-1.png",
    "color": "yellow",
    "numberOfLike": 143,
    "origin": "Brazil",
    "category": "Oncidium"
  },
  {
    "id": "9",
    "name": "Lan cattleya",
    "desc": "Cattleya được mệnh danh là nữ hoàng của các loài hoa lan.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": true,
    "image": "https://cdn.eva.vn/upload/3-2021/images/2021-09-06/image2-1630895145-52-width600height500.jpg",
    "color": "pink",
    "numberOfLike": 289,
    "origin": "South America",
    "category": "Cattleya"
  },
  {
    "id": "10",
    "name": "Lan hoàng thảo",
    "desc": "Lan hoàng thảo với vẻ đẹp rực rỡ và hương thơm ngọt ngào.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://cdn.tgdd.vn/Files/2021/03/29/1340770/hoa-lan-hoang-thao-dep_800x420.jpg",
    "color": "yellow",
    "numberOfLike": 156,
    "origin": "Vietnam",
    "category": "Dendrobium"
  },
  {
    "id": "11",
    "name": "Lan kim tuyến",
    "desc": "Lan kim tuyến quý hiếm với những đường gân ánh vàng như tơ.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": true,
    "image": "https://cayxanh.com.vn/wp-content/uploads/2019/10/hoa-lan-kim-tuyen.jpg",
    "color": "gold",
    "numberOfLike": 210,
    "origin": "Vietnam",
    "category": "Paphiopedilum"
  },
  {
    "id": "12",
    "name": "Lan bạch ngọc",
    "desc": "Lan bạch ngọc với sắc trắng tinh khôi như ngọc, rất được yêu thích.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhdep.net/wp-content/uploads/2019/07/hoa-lan-bach-ngoc.jpg",
    "color": "white",
    "numberOfLike": 188,
    "origin": "Thailand",
    "category": "Phalaenopsis"
  },
  {
    "id": "13",
    "name": "Lan thủy tiên",
    "desc": "Lan thủy tiên với hương thơm quyến rũ và sắc vàng tươi sáng.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhnet.vn/wp-content/uploads/2020/07/hoa-lan-thuy-tien.jpg",
    "color": "yellow",
    "numberOfLike": 132,
    "origin": "Taiwan",
    "category": "Cymbidium"
  },
  {
    "id": "14",
    "name": "Lan vân hồ",
    "desc": "Lan vân hồ mang sắc hồng mơ màng như làn mây buổi sớm.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://khuvuonxanh.vn/wp-content/uploads/2021/05/hoa-lan-van-ho.jpg",
    "color": "pink",
    "numberOfLike": 145,
    "origin": "Vietnam",
    "category": "Cattleya"
  },
  {
    "id": "15",
    "name": "Lan diệp quang",
    "desc": "Lan diệp quang nổi bật với những đốm sáng lấp lánh trên cánh hoa.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhsanvuon.com/wp-content/uploads/2022/03/hoa-lan-diep-quang.jpg",
    "color": "purple",
    "numberOfLike": 195,
    "origin": "Singapore",
    "category": "Vanda"
  },
  {
    "id": "16",
    "name": "Lan mùa xuân",
    "desc": "Lan mùa xuân nở rộ đón chào năm mới với sắc hồng rực rỡ.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhviet.com/wp-content/uploads/2020/12/hoa-lan-mua-xuan.jpg",
    "color": "pink",
    "numberOfLike": 167,
    "origin": "China",
    "category": "Cymbidium"
  },
  {
    "id": "17",
    "name": "Lan hỏa tiễn",
    "desc": "Lan hỏa tiễn với hình dáng độc đáo như những tia lửa đang bắn lên.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhdep.net/wp-content/uploads/2021/09/hoa-lan-hoa-tien.jpg",
    "color": "red",
    "numberOfLike": 98,
    "origin": "Thailand",
    "category": "Oncidium"
  },
  {
    "id": "18",
    "name": "Lan thạch hộc",
    "desc": "Lan thạch hộc thường mọc trên đá, tượng trưng cho sức sống mãnh liệt.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhtot.com/wp-content/uploads/2021/04/hoa-lan-thach-hoc.jpg",
    "color": "white",
    "numberOfLike": 112,
    "origin": "Vietnam",
    "category": "Dendrobium"
  },
  {
    "id": "19",
    "name": "Lan ngọc thạch",
    "desc": "Lan ngọc thạch với vẻ đẹp quý phái như những viên ngọc trong vương miện.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhnet.vn/wp-content/uploads/2022/06/hoa-lan-ngoc-thach.jpg",
    "color": "green",
    "numberOfLike": 203,
    "origin": "Japan",
    "category": "Phalaenopsis"
  },
  {
    "id": "20",
    "name": "Lan huyết nhung",
    "desc": "Lan huyết nhung mang sắc đỏ thẫm như màu nhung quý hiếm.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhdep.net/wp-content/uploads/2023/01/hoa-lan-huyet-nhung.jpg",
    "color": "red",
    "numberOfLike": 178,
    "origin": "Vietnam",
    "category": "Cattleya"
  },
  {
    "id": "21",
    "name": "Lan tuyết sơn",
    "desc": "Lan tuyết sơn với sắc trắng tinh khiết như tuyết trên đỉnh núi.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhviet.com/wp-content/uploads/2021/07/hoa-lan-tuyet-son.jpg",
    "color": "white",
    "numberOfLike": 156,
    "origin": "Nepal",
    "category": "Cymbidium"
  },
  {
    "id": "22",
    "name": "Lan sao băng",
    "desc": "Lan sao băng với hình dáng độc lạ như những vì sao đang rơi.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhtot.com/wp-content/uploads/2022/11/hoa-lan-sao-bang.jpg",
    "color": "purple",
    "numberOfLike": 234,
    "origin": "Brazil",
    "category": "Oncidium"
  },
  {
    "id": "23",
    "name": "Lan hồng đào",
    "desc": "Lan hồng đào với sắc hồng rực rỡ, tượng trưng cho tình yêu đôi lứa.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://khuvuonxanh.vn/wp-content/uploads/2023/03/hoa-lan-hong-dao.jpg",
    "color": "pink",
    "numberOfLike": 145,
    "origin": "Vietnam",
    "category": "Phalaenopsis"
  },
  {
    "id": "24",
    "name": "Lan hoàng gia",
    "desc": "Lan hoàng gia với vẻ đẹp uy nghi và sang trọng bậc nhất.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": true,
    "image": "https://caycanhnet.vn/wp-content/uploads/2023/05/hoa-lan-hoang-gia.jpg",
    "color": "gold",
    "numberOfLike": 267,
    "origin": "Thailand",
    "category": "Vanda"
  },
  {
    "id": "25",
    "name": "Lan thuần khiết",
    "desc": "Lan thuần khiết với sắc trắng ngần như tâm hồn trong sáng.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhdep.net/wp-content/uploads/2023/07/hoa-lan-thuan-khiet.jpg",
    "color": "white",
    "numberOfLike": 134,
    "origin": "Vietnam",
    "category": "Paphiopedilum"
  },
  {
    "id": "26",
    "name": "Lan nhiệt đới",
    "desc": "Lan nhiệt đới với màu sắc rực rỡ và sức sống mãnh liệt.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhviet.com/wp-content/uploads/2023/09/hoa-lan-nhiet-doi.jpg",
    "color": "orange",
    "numberOfLike": 123,
    "origin": "Colombia",
    "category": "Cattleya"
  },
  {
    "id": "27",
    "name": "Lan ánh ngọc",
    "desc": "Lan ánh ngọc lấp lánh như những viên ngọc quý dưới ánh mặt trời.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhtot.com/wp-content/uploads/2023/11/hoa-lan-anh-ngoc.jpg",
    "color": "blue",
    "numberOfLike": 198,
    "origin": "Myanmar",
    "category": "Vanda"
  },
  {
    "id": "28",
    "name": "Lan giáng hương",
    "desc": "Lan giáng hương với hương thơm nồng nàn quyến rũ lòng người.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": true,
    "image": "https://khuvuonxanh.vn/wp-content/uploads/2024/01/hoa-lan-giang-huong.jpg",
    "color": "yellow",
    "numberOfLike": 245,
    "origin": "Vietnam",
    "category": "Dendrobium"
  },
  {
    "id": "29",
    "name": "Lan tân thế giới",
    "desc": "Lan tân thế giới đại diện cho sự khởi đầu mới và hy vọng.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhnet.vn/wp-content/uploads/2024/03/hoa-lan-tan-the-gioi.jpg",
    "color": "pink",
    "numberOfLike": 156,
    "origin": "USA",
    "category": "Cymbidium"
  },
  {
    "id": "30",
    "name": "Lan quý báu",
    "desc": "Lan quý báu với vẻ đẹp sang trọng và giá trị cao quý.",
    "rating": 5,
    "isSpecial": true,
    "isNatural": false,
    "image": "https://caycanhdep.net/wp-content/uploads/2024/05/hoa-lan-quy-bau.jpg",
    "color": "purple",
    "numberOfLike": 276,
    "origin": "Thailand",
    "category": "Phalaenopsis"
  },
  {
    "id": "31",
    "name": "Lan thiên nhiên",
    "desc": "Lan thiên nhiên mang vẻ đẹp hoang sơ và thuần khiết.",
    "rating": 4,
    "isSpecial": false,
    "isNatural": true,
    "image": "https://caycanhviet.com/wp-content/uploads/2024/07/hoa-lan-thien-nhien.jpg",
    "color": "green",
    "numberOfLike": 112,
    "origin": "Vietnam",
    "category": "Paphiopedilum"
  }
];